services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ADDR: 0.0.0.0:8080
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - air-tmp:/app/tmp
    working_dir: /app
    command: air -c .air.toml

  db:
    image: postgres:16-alpine
    container_name: todo-backend-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  go-mod-cache:
  air-tmp:
  postgres-data:
